# docker-compose.yml
version: "3.8"

services:
  strong-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUN_UID: ${HOST_UID:-1000}
        RUN_GID: ${HOST_GID:-1000}
    image: strong-agent:latest
    container_name: strong-agent
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # セキュアな値は .env（Compose の env_file）や Docker Secrets (下)で渡す事を推奨
      - NODE_ENV=production
      - AGENT_WORKSPACE_PATH=/workspace
      - AGENT_APPROVAL_REQUIRED=${AGENT_APPROVAL_REQUIRED:-true}
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key
    # 推奨: secrets を使って機微情報を取り扱う（Docker Compose の secrets 機能）
    secrets:
      - openai_api_key
    volumes:
      # ホスト側 projects は読み取り専用でマウントし、Agent は workspace に成果を出す運用を推奨
      - ./projects:/projects:ro
      - ./workspace:/workspace
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M

secrets:
  openai_api_key:
    file: ./secrets/openai_api_key.txt
    # external: true  # 既存の Docker Secret を使う場合はこちらを有効にし、file 行をコメントアウト